export const client = {
  name: "Sunrise Landscaping",
  tagline: "Professional landscaping services in Irvine",
  phone: "(949) 123-4567",
  email: "john@sunrise.com",
  address: "123 Main St.",
  city: "Irvine",
  state: "CA",
  serviceArea: ["Irvine"],
  primaryColor: "#1a3a5c",
  industry: "landscaping",
  services: ["Lawn care","Garden design","Irrigation","Tree trimming","Mulching","Sod installation","Leaf removal"],
  cmsUrl: "https://cms.sebvia.com",
  tenantSlug: "sunrise-landscaping",
  googleAnalyticsId: '',
  domain: "sunrise.sebvia.com",
};
